### ISSUE TITLE
False positive version check

### ISSUE THREAD

**Issue by knubie** [liquidz/vim-iced-asyncomplete#1]
Received the following error: `iced-asyncomplete: vim-iced v0.11.1 or later is required.`

Although I'm using the latest version of vim-iced.

**Comment by liquidz** [comment]
@knubie Thanks for your reporting!
It works well in my environment, and I couldn't reproduce the problem.

Version verification is a very simple logic as follows.
* https://github.com/liquidz/vim-iced-asyncomplete/blob/master/ftplugin/clojure.vim#L10-L11
* https://github.com/liquidz/vim-iced/blob/master/ftplugin/clojure.vim#L5

So
* Do you have any other error messages in `:messages` command result?
* Are you loading plugins in the right order?
  * vim-iced must be loaded before vim-iced-asyncomplete.
  * c.f. https://github.com/junegunn/vim-plug/wiki/faq#managing-dependencies

BTW, minimal configuration may useful for debugging.
https://liquidz.github.io/vim-iced/#minimal_configuration

**Comment by knubie** [comment]
> - Are you loading plugins in the right order?
>    - vim-iced must be loaded before vim-iced-asyncomplete.

That was it! Thanks for helping me debug. 😊
